In [17]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [18]:
cars_data = pd.read_csv('C:/Users/User/Desktop/dataset.csv')

In [19]:
cars_data.head()

,name,description,make,model,year,price,engine,cylinders,fuel,mileage,transmission,trim,body,doors,exterior_color,interior_color,drivetrain
0,Jeep Wagoneer Series II,"\n \n Heated Leather Seats, Nav Sy...",Jeep,Wagoneer,2024,74600.0,24V GDI DOHC Twin Turbo,6.0,Gasoline,10.0,8-Speed Automatic,Series II,SUV,4.0,White,Global Black,Four-wheel Drive
1,Jeep Grand Cherokee Laredo,Al West is committed to offering every custome...,Jeep,Grand Cherokee,2024,50170.0,OHV,6.0,Gasoline,1.0,8-Speed Automatic,Laredo,SUV,4.0,Metallic,Global Black,Four-wheel Drive
2,GMC Yukon XL Denali,NaN,GMC,Yukon XL,2024,96410.0,"6.2 V-8 gasoline direct injection, variable va...",8.0,Gasoline,0.0,Automatic,Denali,SUV,4.0,Summit White,Teak/Light Shale,Four-wheel Drive
3,Dodge Durango Pursuit,White Knuckle Clearcoat 2023 Dodge Durango Pur...,Dodge,Durango,2023,46835.0,16V MPFI OHV,8.0,Gasoline,32.0,8-Speed Automatic,Pursuit,SUV,4.0,White Knuckle Clearcoat,Black,All-wheel Drive
4,RAM 3500 Laramie,\n \n 2024 Ram 3500 Laramie Billet...,RAM,3500,2024,81663.0,24V DDI OHV Turbo Diesel,6.0,Diesel,10.0,6-Speed Automatic,Laramie,Pickup Truck,4.0,Silver,Black,Four-wheel Drive

In [20]:
cars_data.drop(columns=['description'], inplace=True)

In [21]:
cars_data.drop(columns=['make'], inplace=True)

In [22]:
cars_data.drop(columns=['model'], inplace=True)

In [23]:
cars_data.drop(columns=['trim'], inplace=True)

In [24]:
cars_data.drop(columns=['body'], inplace=True)

In [25]:
cars_data.drop(columns=['exterior_color'], inplace=True)

In [26]:
cars_data.drop(columns=['interior_color'], inplace=True)

In [27]:
cars_data.head()

,name,year,price,engine,cylinders,fuel,mileage,transmission,doors,drivetrain
0,Jeep Wagoneer Series II,2024,74600.0,24V GDI DOHC Twin Turbo,6.0,Gasoline,10.0,8-Speed Automatic,4.0,Four-wheel Drive
1,Jeep Grand Cherokee Laredo,2024,50170.0,OHV,6.0,Gasoline,1.0,8-Speed Automatic,4.0,Four-wheel Drive
2,GMC Yukon XL Denali,2024,96410.0,"6.2 V-8 gasoline direct injection, variable va...",8.0,Gasoline,0.0,Automatic,4.0,Four-wheel Drive
3,Dodge Durango Pursuit,2023,46835.0,16V MPFI OHV,8.0,Gasoline,32.0,8-Speed Automatic,4.0,All-wheel Drive
4,RAM 3500 Laramie,2024,81663.0,24V DDI OHV Turbo Diesel,6.0,Diesel,10.0,6-Speed Automatic,4.0,Four-wheel Drive

In [16]:
cars_data.shape

(1002, 10)

In [ ]:
#preprocessing

In [ ]:
#Null check

In [28]:
cars_data.isnull().sum()

name              0
year              0
price            23
engine            2
cylinders       105
fuel              7
mileage          34
transmission      2
doors             7
drivetrain        0
dtype: int64

In [29]:
cars_data.dropna(inplace=True)

In [30]:
cars_data.shape

(839, 10)

In [ ]:
#Duplicate check

In [31]:
cars_data.duplicated().sum()

np.int64(47)

In [32]:
cars_data.drop_duplicates(inplace=True)

In [33]:
cars_data.shape

(792, 10)

In [34]:
cars_data

,name,year,price,engine,cylinders,fuel,mileage,transmission,doors,drivetrain
0,Jeep Wagoneer Series II,2024,74600.0,24V GDI DOHC Twin Turbo,6.0,Gasoline,10.0,8-Speed Automatic,4.0,Four-wheel Drive
1,Jeep Grand Cherokee Laredo,2024,50170.0,OHV,6.0,Gasoline,1.0,8-Speed Automatic,4.0,Four-wheel Drive
2,GMC Yukon XL Denali,2024,96410.0,"6.2 V-8 gasoline direct injection, variable va...",8.0,Gasoline,0.0,Automatic,4.0,Four-wheel Drive
3,Dodge Durango Pursuit,2023,46835.0,16V MPFI OHV,8.0,Gasoline,32.0,8-Speed Automatic,4.0,All-wheel Drive
4,RAM 3500 Laramie,2024,81663.0,24V DDI OHV Turbo Diesel,6.0,Diesel,10.0,6-Speed Automatic,4.0,Four-wheel Drive
...,...,...,...,...,...,...,...,...,...,...
996,RAM 2500 Tradesman,2024,69315.0,24V DDI OHV Turbo Diesel,6.0,Diesel,0.0,Automatic,4.0,Four-wheel Drive
997,Mercedes-Benz Sprinter 2500 Standard Roof,2024,59037.0,16V DDI DOHC Turbo Diesel,4.0,Diesel,10.0,9-Speed Automatic,3.0,Rear-wheel Drive
999,Jeep Wagoneer Base,2024,69085.0,24V GDI DOHC Twin Turbo,6.0,Gasoline,20.0,8-Speed Automatic,4.0,Four-wheel Drive
1000,Nissan Murano SV Intelligent AWD,2024,43495.0,"6 DOHC, variable valve control, regular unlead...",6.0,Gasoline,6.0,Automatic,4.0,All-wheel Drive
1001,Chevrolet Silverado 2500 WT,2024,48995.0,"8 gasoline direct injection, variable valve co...",8.0,Gasoline,31.0,Automatic,4.0,Rear-wheel Drive

In [35]:
cars_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 792 entries, 0 to 1001
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          792 non-null    object
 1   year          792 non-null    int64
 2   price         792 non-null    float64
 3   engine        792 non-null    object
 4   cylinders     792 non-null    float64
 5   fuel          792 non-null    object
 6   mileage       792 non-null    float64
 7   transmission  792 non-null    object
 8   doors         792 non-null    float64
 9   drivetrain    792 non-null    object
dtypes: float64(4), int64(1), object(5)
memory usage: 68.1+ KB

In [ ]:
#Data Analysis

In [37]:
for col in cars_data.columns:
    print('unique values of ' + col)
    print(cars_data[col].unique())
    print('========================')

unique values of name
['Jeep Wagoneer Series II' 'Jeep Grand Cherokee Laredo'
 'GMC Yukon XL Denali' 'Dodge Durango Pursuit' 'RAM 3500 Laramie'
 'Nissan Murano Platinum' 'Jeep Wagoneer Base'
 'Ford F-350 Lariat Super Duty' 'Hyundai Tucson Hybrid Limited'
 'Jeep Grand Cherokee Altitude' 'Jeep Compass Latitude'
 'RAM 3500 Tradesman' 'Hyundai Santa Cruz 2.5T Limited'
 'Hyundai Santa Cruz 2.5T XRT' 'Ford Explorer Timberline'
 'Volkswagen Taos 1.5T SE' 'Volkswagen Jetta 1.4T S' 'Dodge Hornet R/T'
 'Hyundai Tucson SEL' 'GMC Terrain Denali' 'Hyundai Santa Cruz 2.5L SEL'
 'Ford Explorer XLT' 'Jeep Compass Limited' 'RAM 2500 Tradesman'
 'Nissan Murano SV' 'Ford Transit-250 148 WB Medium Roof Cargo'
 'Jeep Grand Cherokee 4xe Trailhawk' 'Volkswagen Jetta 1.4T SE'
 'Chevrolet Silverado 1500 RST' 'Kia Seltos EX' 'Chevrolet Blazer 3LT'
 'GMC Terrain SLE' 'Jeep Wrangler Sport S' 'Mazda CX-90 PHEV Preferred'
 'Acura MDX Advance' 'Volkswagen Atlas Cross Sport 2.0T SEL'
 'Hyundai Sonata Hybrid Limited' 'Dodge Durango R/T'
 'Dodge Hornet R/T EAWD' 'Dodge Hornet GT' 'Kia Sportage Hybrid EX'
 'Ford Expedition XLT'
 'Volkswagen Atlas 2.0T Peak Edition SE w/Technology'
 'Hyundai Tucson Limited' 'BMW X7 xDrive40i'
 'Toyota Tundra Hybrid Limited' 'Nissan Kicks SV'
 'Buick Envista Preferred' 'Acura MDX Base' 'Nissan Rogue SV'
 'Jeep Wagoneer L Series II Carbide 4x4' 'Kia Sportage S'
 'Nissan Rogue SL' 'Dodge Durango GT' 'Hyundai Sonata SEL'
 'GMC Terrain SLT' 'Audi SQ5 Premium Plus'
 "RAM 3500 Tradesman Crew Cab 4x4 8' Box" 'Audi Q5 e 55 Premium Plus'
 'Mazda CX-90 PHEV Premium Plus' 'Dodge Hornet R/T Plus'
 'Chevrolet Silverado 1500 Custom' 'Chevrolet Silverado 1500 LT'
 'Chevrolet Silverado 1500 WT' 'Dodge Charger SXT'
 'Mercedes-Benz Sprinter 2500 Standard Roof'
 'Honda CR-V Hybrid Sport Touring' 'Hyundai Tucson Hybrid SEL Convenience'
 'Kia Sportage X-Line' 'Jeep Compass Sport' 'Ford Transit-150 Base'
 'Jeep Wrangler 4-Door Sahara 4x4' 'Hyundai Tucson Hybrid Blue'
 'Dodge Charger Scat Pack' 'Jeep Grand Cherokee 4xe 4x4'
 'Chevrolet Equinox LS' 'Jeep Wrangler 4xe Rubicon'
 'Mazda CX-90 PHEV Base' 'RAM ProMaster 2500 High Roof'
 'Lincoln Corsair Reserve' 'GMC Savana 2500 Work Van'
 'Chrysler Pacifica Hybrid Select' 'Acura ZDX A-SPEC'
 'Nissan Altima 2.5 SV' 'Hyundai Sonata Hybrid SEL' 'Dodge Hornet GT AWD'
 'Jeep Grand Cherokee 4xe Anniversary Edition'
 'Dodge Hornet Hornet Gt Awd' 'Jeep Wrangler 4xe Sport S'
 'Jeep Grand Cherokee Limited' 'RAM ProMaster 3500 High Roof'
 'Cadillac XT5 Luxury' 'Jeep Wrangler 4xe Sport' 'Acura MDX Technology'
 'Jeep Wrangler Rubicon' 'Jeep Gladiator Rubicon' 'Volkswagen Taos 1.5T S'
 'INFINITI QX50 LUXE' 'Nissan Versa 1.6 SV'
 'Mercedes-Benz AMG GLE 53 Base' 'Mazda CX-90 PHEV Premium'
 'Ford F-350 XL' 'Audi A5 Sportback S line Premium Plus'
 'Chevrolet Trailblazer RS' 'Jeep Wrangler 4xe Sahara'
 'Ford Escape Active' 'Ford Bronco Sport Outer Banks'
 'Jeep Grand Cherokee L Laredo' 'Jeep Wagoneer L Series II'
 'Hyundai Elantra HEV Blue' "RAM 3500 Laramie Crew Cab 4x4 8' Box"
 'Volkswagen Atlas Cross Sport 2.0T SEL R-Line'
 'RAM 3500 Tradesman/SLT/Laramie/Limited'
 'Lexus RX 500h F SPORT PERFORMANCE'
 "RAM 3500 Laramie Mega Cab 4x4 6'4' Box"
 'Chevrolet Silverado 1500 LT Trail Boss' 'Nissan Versa 1.6 SR'
 'Kia Sportage EX' 'Hyundai Tucson Hybrid N Line' 'Nissan Kicks SR'
 'Volkswagen Taos 1.5T SEL' 'Jeep Grand Cherokee L Limited'
 'Dodge Hornet Hornet R/T Plus Eawd' 'Mazda MX-5 Miata RF Grand Touring'
 'Honda CR-V Hybrid Sport-L' 'RAM 2500 Big Horn'
 'Jeep Grand Cherokee L Altitude' 'Chevrolet Silverado 2500 LT'
 'RAM 2500 Laramie' 'GMC Sierra 3500 SLT' 'Jeep Grand Cherokee 4xe Base'
 'Subaru Legacy Premium' 'BMW M235 Gran Coupe i xDrive'
 'RAM 3500 Big Horn' 'Honda CR-V Hybrid Sport' 'Ford Expedition Limited'
 'Ford Expedition Timberline' 'Kia Sportage SX'
 'Kia Sportage X-Pro Prestige' 'Land Rover Range Rover Evoque Dynamic SE'
 'Honda Odyssey Elite' 'RAM 2500 Longhorn' 'Chevrolet Equinox FWD RS'
 'GMC Sierra 2500 Denali'
 'Audi Q5 e Premium 55 TFSI e S line quattro S tronic' 'Nissan Titan SV'
 'Ford Edge ST-Line' 'Volkswagen Jetta 1.5T SE' 'Chevrolet Equinox 1LT'
 'Hyundai Santa Cruz 2.5T NIGHT' 'Land Rover Discovery Sport Dynamic SE'
 'Mercedes-Benz Sprinter 3500 170 WB High Roof Extended Cargo'
 'Volvo XC90 Recharge Plug-In Hybrid T8 Plus Bright Theme 7 Passenger'
 'Cadillac XT5 Premium Luxury' 'Kia Sorento SX'
 'Jeep Wagoneer L Series III' 'Nissan Frontier SV' 'Chevrolet Equinox RS'
 'Honda HR-V LX' 'Kia Niro Touring' 'Buick Encore GX Avenir'
 'Ford Edge SEL' 'Mercedes-Benz GLE 450 4MATIC'
 'Mercedes-Benz GLS 450 4MATIC' 'Ford Transit-250 Base'
 'Chevrolet Trax LT' 'Jeep Wrangler 4xe Rubicon X' 'Honda Odyssey Touring'
 'Chevrolet Silverado 1500 Custom Trail Boss'
 'Chrysler Pacifica Touring L' 'Ford Bronco Sport Big Bend'
 'Jeep Grand Cherokee L Overland' 'Land Rover Defender P400 X-Dynamic SE'
 'Chrysler Pacifica Touring-L' 'Jeep Gladiator Sport' 'GMC Yukon XL SLT'
 'Audi Q5 e 55 Prestige' 'BMW X7 M60i' 'Kia Sorento Hybrid EX'
 'Dodge Hornet GT Plus AWD' 'Kia Seltos S' 'Jeep Compass Latitude Lux'
 'Kia Niro SX Touring' 'Buick Envision Preferred' 'Ford Escape ST-Line'
 'Ford Escape S' 'Ford Bronco Wildtrak' 'Kia Niro EX'
 'Ford Expedition Platinum' 'Volkswagen Jetta 1.5T S'
 'Dodge Hornet R/T Plus EAWD' 'Hyundai Palisade SEL'
 'RAM 2500 Power Wagon' 'BMW 740 i' 'Jeep Grand Cherokee 4xe Summit'
 'Nissan Versa S' 'Ford Escape ST-Line Elite' 'Buick Envision Essence'
 'Honda Passport TrailSport' 'Chevrolet Silverado 1500 ZR2'
 'Jeep Grand Cherokee Summit' 'Honda Odyssey EX-L'
 'Hyundai Elantra HEV Limited' 'Volkswagen Jetta 1.5T SEL'
 'RAM ProMaster 3500 Base' 'Toyota Corolla Cross LE'
 'Mercedes-Benz Sprinter 2500 High Roof' 'Jeep Grand Wagoneer Series III'
 'Toyota Tundra Hybrid 1794 Edition' 'Hyundai Kona SEL'
 'INFINITI QX55 SENSORY' 'Volkswagen Jetta 1.4T SEL'
 'Hyundai Kona Limited' 'Toyota Tundra Hybrid Platinum' 'Ford F-150 XLT'
 'RAM 2500 Tradesman 4x4 Crew Cab 8 Box' 'Audi A3 Premium'
 'Ford F-150 STX' 'Nissan Kicks S' 'Mercedes-Benz Sprinter 3500 High Roof'
 'Ford Explorer Platinum' 'INFINITI QX50 SPORT' 'Buick Enclave Premium'
 'Chrysler Pacifica Limited' 'Audi A5 Sportback S line Premium'
 'Ford Edge SE' 'Ford Edge Titanium' 'Nissan Sentra SV'
 'GMC Sierra 3500 Denali' 'Hyundai Kona N Line' 'Toyota RAV4 Prime XSE'
 'Jeep Grand Wagoneer Series II' 'Mercedes-Benz Sprinter 2500 Crew 144 WB'
 'GMC Sierra 2500 Pro' 'Jeep Wagoneer Series III'
 'Dodge Hornet Hornet R/T Eawd' 'Hyundai Santa Cruz 2.5L SE'
 'Chrysler Voyager LX' 'GMC Sierra 1500 SLT' 'Ford Transit Connect XLT'
 'Jeep Compass Trailhawk' 'GMC Sierra 2500 Denali Ultimate'
 'Ford Maverick Lariat' 'Jeep Wagoneer L Base'
 'GMC Sierra 1500 Denali Ultimate' 'GMC Terrain AT4'
 'Ford Transit-350 Base' 'Kia Sorento LX' 'Nissan Pathfinder SL 4WD'
 'Ford Transit-350 ' 'Dodge Hornet GT Plus'
 'Mercedes-Benz Sprinter 2500 144 WB Standard Roof Crew' 'Kia Seltos SX'
 'Buick Envista Sport Touring' 'Ford Bronco Sport Free Wheeling'
 'Mercedes-Benz GLA 250 Base 4MATIC' 'Ford Expedition King Ranch'
 'Mercedes-Benz Sprinter 2500 144 WB Standard Roof Passenger'
 'Kia Telluride SX X-Pro' 'Mazda CX-90 3.3 Turbo Premium Plus'
 'Kia Sportage SX-Prestige' 'Mazda CX-90 3.3 Turbo S Premium'
 'Volvo S60 Recharge Plug-In Hybrid T8 Plus Dark Theme' 'Kia Sorento EX'
 'Ford Escape Platinum' 'Cadillac XT6 Luxury FWD' 'Subaru Impreza Sport'
 'Mazda CX-70 3.3 Turbo S Premium' 'Nissan Murano SL' 'BMW X3 sDrive30i'
 "RAM 2500 Tradesman Regular Cab 4x4 8' Box"
 'Volvo C40 Recharge Pure Electric Twin Ultimate'
 'RAM ProMaster 1500 Low Roof' 'Subaru Impreza RS' 'Honda CR-V EX-L'
 'Kia Soul S' 'Chrysler 300 Touring L'
 'Mercedes-Benz AMG C 43 Base 4MATIC' 'Ford Maverick XLT'
 'Hyundai Kona SE' 'Jeep Grand Cherokee 4xe Overland'
 'Nissan Murano SV Intelligent AWD' 'Chevrolet Silverado 2500 WT']
========================
unique values of year
[2024 2023 2025]
========================
unique values of price
[ 74600.  50170.  96410.  46835.  81663.  46000.  63862.  89978.  42230.
  42773.  37743.  60904.  43419.  44022.  38574.  48000.  53190.  32751.
  24348.  65221.  39491.  30305.  44120.  33160.  40940.  34084.  58855.
  39867.  53595.  59547.  27175.  58610.  29640.  43727.  35870.  64670.
  46973.  54905.  50915.  65595.  28860.  51721.  38870.  58709.  42855.
  34990.  34835.  69955.  39581.  49166.  40474.  89450.  62341.  24500.
  27075.  51645.  35975.  36405.  86137.  27969.  63223.  47785.  41180.
  44720.  44160.  28469.  58930.  35236.  60555.      0.  66334.  73020.
  89555.  65315.  58599.  47234.  44161.  49496.  43475.  36083.  54559.
  60061.  28867.  42005.  35864.  30000.  34000.  29342.  55645.  59456.
  39714.  49628.  33089.  65075.  38980.  58235.  27998.  25515.  66960.
  53395.  53272.  51361.  44595.  60600.  38575.  69850.  31225.  32520.
  35821.  60200.  36532.  61506.  59625.  35480.  31200.  54835.  52115.
  32011.  53099.  30383.  46890.  37729.  53535.  37490.  44600.  45038.
  56155.  60972.  53796.  41497.  25311.  35913.  48350.  21000.  44620.
  90995.  56079.  52263.  42991.  54910.  56105.  44790.  32580.  34330.
  37430.  42015.  32925.  57870.  28265.  30618.  31985.  35210.  31721.
  44852.  32485.  39370.  45844.  78543.  27080.  83940.  48541.  81036.
  54949.  67562.  58399.  73270.  89040.  65175.  20389.  50599.  31190.
  35404.  35656.  32660.  61860.  26600.  37325.  52642.  40235.  42064.
  39832.  41036.  33331.  51835.  47340.  54209.  86505.  48595.  38040.
  52950.  52567.  87488.  44737.  41995.  38855.  58909.  65350.  49411.
  50590.  70190.  59542.  53445.  79675.  87075.  34799.  67125.  46721.
  56119.  28193.  58949.  31042.  54449.  77885.  31535.  50349.  56345.
  50675.  64516.  36480.  26104.  42790.  54545.  65774.  34305.  44621.
  39763.  67237.  36900.  90350.  83910.  49944.  32433.  33095.  39990.
  62145.  48364.  83374.  31222.  85845.  30034.  44170.  69995.  27554.
  45716.  42715.  36970.  26329.  30101.  54899.  32198.  54585.  35999.
  36882.  45055.  69697.  51083.  27400.  52445.  34600.  47165.  50184.
  40380.  55353.  72357.  34492.  36000.  53160.  59116.  67510.  48187.
  25923.  50702.  75595.  51845.  60915.  71167.  41975.  48861.  31537.
  47175.  51585.  86097.  37946.  31301.  63010.  50030.  42990.  32635.
  46672.  27450.  34310.  36190.  57849.  44615.  34985.  53890.  35364.
  35885.  85630.  47530.  49632.  55439.  98180.  44604.  57650.  32269.
  45051.  57508.  51803.  56800.  52631.  38500.  24680.  54490.  80095.
  44350.  66375.  57635.  45300.  34637.  87190.  55399.  41391.  30020.
  66360.  26500.  53995.  77645.  58648.  46450.  41195.  46791.  76648.
  78695. 115445.  34182.  39390.  38546.  28630.  61865.  26860.  29826.
  42597.  37135.  52180.  33590.  41765.  50377.  65416.  43299.  47744.
  53455.  52853.  69035.  31860.  64214.  82523.  43135.  35490.  33109.
  46670.  88135.  54210.  43585.  49550.  22260.  84860.  71846.  46490.
  49180.  35683.  84190.  71999.  47080.  54226.  33255.  48612.  90945.
  37100.  59205.  31390.  46905.  36499.  74990.  40355.  43000. 103045.
  28997.  29066.  33092.  47100.  32406.  40145.  24600.  69201.  17994.
  40630.  49075.  23160.  67784.  40449.  30188.  59420.  60080.  42785.
  47280.  30525.  44850.  47105.  38736.  58230.  67190.  30278.  34572.
  30955.  34698.  32138.  61248.  40925.  76475.  65360.  47650.  41705.
  30335.  33695.  29374.  35744.  25975.  68256.  67749.  49735.  49885.
  30499.  54939.  58665. 124250.  65129.  47225.  31610.  72977.  36734.
  61330.  32009.  49229.  54200.  25999.  56995.  34472.  25410.  29895.
  68095.  65260.  40980.  37275.  72294.  51625.  30829.  44826.  38122.
  47451.  58840.  32837.  54403.  71146.  84935.  52495.  61481.  51700.
  42947.  34329.  62154.  39375.  65295.  64930.  47142.  41955.  36860.
  76300.  45605.  24305.  46870.  33840.  50058.  37505.  33005.  53700.
  62295.  90220.  33696.  54641.  32750.  50595.  53915.  77473.  49404.
  30870.  56872.  34730.  55183.  32625.  20849.  52405.  67159.  40260.
  95230.  35835.  35775.  72600.  47410.  30935.  27087.  78895.  44710.
  21637.  28535.  50923.  21889.  29182.  21123.  63518.  79934.  46243.
  42876. 102287.  55020.  40344.  33491.  40754.  83640.  50209.  69720.
  88478.  35389.  36600. 110150.  67105.  50955.  40434.  30740.  66902.
  54190.  47763.  68600.  74290.  33668.  89595.  43524.  33071.  30490.
  61006.  43684.  38954.  59466.  38036.  60573.  59620.  41230.  29111.
  96860.  34635.  41045.  79487.  74366.  40979.  39025.  81160.  21195.
  63440.  33969.  38598.  84405.  52810.  63145.  34940.  37498.  58950.
  41890.  38000.  57000.  48201.  73360.  64111.  46855.  58779.  45995.
  42155.  54525.  47030.  42425.  42436.  56015.  52350.  25950.  46350.
  33375.  39935.  35435.  36810.  35585.  40375.  41720.  62255.  57835.
 108537.  63609.  64025.  86420.  77525.  36195.  35040.  64434.  67422.
  61179.  67650.  61276.  94895.  31490.  70115.  77522.  24105.  28000.
  33390.  60884.  40880.  39555.  35077.  47290.  44759.  53710.  86490.
  84701.  88695.  33573.  69017.  60925.  51965.  63670.  35010.  49900.
  75925.  93303.  58049.  49260.  52640.  32491.  51725.  58720.  32995.
  54800.  49285.  49895.  57486.  40085.  57545.  74391.  44876.  64965.
  38481.  77085.  58825.  26335.  49720.  50565.  38717.  50415.  50486.
  40250.  29068.  54620.  46510.  40933.  49395.  53750.  30798.  62240.
  38300.  49201.  29386.  72835.  28994.  36280.  80374.  51380.  28998.
  24979.  50245.  49082.  32098.  53791.  49139.  72135.  37965.  37335.
  33785.  35994.  48268.  45141.  28098.  24430.  25080.  73960.  46659.
  43490.  80927.  33977.  35795.  36550.  37805.  74625.  35400.  43613.
  49836.  27555.  29305.  40015.  35195.  35615.  20842.  43685.  66770.
  48822.  37220.  67164.  37309.  77314.  70312.  36331.  62343.  67446.
  40835.  59674.  69315.  59037.  69085.  43495.  48995.]
========================
unique values of engine
['24V GDI DOHC Twin Turbo' 'OHV'
 '6.2 V-8 gasoline direct injection, variable valve contr' '16V MPFI OHV'
 '24V DDI OHV Turbo Diesel' '24V MPFI DOHC' '32V DDI OHV Turbo Diesel'
 '16V GDI DOHC Turbo Hybrid'
 'ar 3.6L V-6 DOHC, variable valve control, regular unleade'
 '16V GDI DOHC Turbo' 'oled Turbo Diesel I-6 6.7 L/408'
 '16V PDI DOHC Turbo'
 '4 gasoline direct injection, DOHC, variable valve control'
 '16V PDI DOHC' 'DOHC' '24V PDI DOHC Flexible Fuel' '16V GDI OHV'
 '16V MPFI DOHC' '24V GDI DOHC'
 'gasoline direct injection, DOHC, intercooled turbo, premi'
 '16V GDI DOHC Hybrid' '24V GDI SOHC'
 'gasoline direct injection, DOHC, variable valve control,'
 '4 gasoline direct injection, DOHC, Multiair variable valv'
 '4 gasoline direct injection, DOHC, CVVT variable valve co'
 '24V PDI DOHC Twin Turbo'
 'ream 2.5L I-4 port/direct injection, DOHC, CVVT variable'
 '24V GDI DOHC Turbo'
 'MAX 3.4L V-6 port/direct injection, DOHC, variable valve'
 '4 DOHC, CVTCS variable valve control, regular unleaded, e'
 '12V GDI DOHC Turbo'
 'o 1.5L I-3 gasoline direct injection, DOHC, CVTCS variabl'
 'ne 3L I-6 gasoline direct injection, DOHC, variable valve'
 '4 port/direct injection, DOHC, CVVT variable valve contro'
 '6.2L V-8 gasoline direct injection, variable valve contr'
 'oled Turbo Premium Unleaded V-6 3.0 L/183'
 'High Output 6.7L I-6 diesel direct injection, VVT interc'
 'DOHC 16V LEV3-SULEV30' '16V DDI DOHC Turbo Diesel'
 'TIV-G 2.5L I-4 gasoline direct injection, DOHC, variable'
 '6 gasoline direct injection, variable valve control, regu'
 '24V MPFI DOHC Hybrid' 'c' '16V GDI DOHC'
 'ne 2L I-4 gasoline direct injection, DOHC, variable valve'
 'o 2L I-4 port/direct injection, DOHC, variable valve cont'
 '8 variable valve control, regular unleaded, engine with 4'
 '1.3L I-3 gasoline direct injection, DOHC, variable valve'
 't 1.5L I-3 port/direct injection, DOHC, Ti-VCT variable v' 'oBoost'
 '>\n\n    \n    <dt>VIN</dt>\n     ZACNDFAN0R3A12168' '24V VVT'
 '.6L I-4 gasoline direct injection, DOHC, D-CVVT variable'
 '6.7L I-6 diesel direct injection, VVT intercooled turbo,'
 '16V PDI DOHC Turbo Hybrid' '24V DDI DOHC Turbo Diesel'
 'gasoline direct injection, DOHC, i-VTEC variable valve co'
 '6.6L V-8 diesel direct injection, intercooled turbo, die' 'der'
 '12V PDI DOHC Turbo' 'oled Turbo Premium Unleaded I-4 2.0 L/122'
 'ce 5.6L V-8 gasoline direct injection, DOHC, variable val'
 '4 port/direct injection, DOHC, variable valve control, in'
 'Unleaded V-8 5.6 L/339' '12V GDI OHV'
 't 2L I-4 gasoline direct injection, DOHC, variable valve'
 '6 port/direct injection, DOHC, variable valve control, re'
 '6 gasoline direct injection, i-VTEC variable valve contro'
 '6 DOHC, variable valve control, regular unleaded, engine'
 '5.3L V-8 gasoline direct injection, variable valve contr'
 '6 DOHC, VVT variable valve control, engine with cylinder'
 'ar 3.6L V-6 DOHC, VVT variable valve control, regular unl'
 '32V GDI DOHC Twin Turbo' '24V DOHC'
 'diesel direct injection, DOHC, intercooled turbo, diesel,'
 '24V PDI DOHC Twin Turbo Hybrid' 'EcoBoost'
 '<dt>VIN</dt>\n     1FMUK7HH1SGA05728' 'ER'
 '<dt>VIN</dt>\n     3C63R3HLXRG198198'
 'ream 1.6L I-4 gasoline direct injection, DOHC, CVVD varia'
 '16V PDI DOHC Hybrid'
 'gasoline direct injection, DOHC, iVCT variable valve cont'
 '4 DOHC, variable valve control, regular unleaded, engine'
 '6 gasoline direct injection, DOHC, variable valve control'
 'rbo Regular Unleaded I-6 3.0 L/183'
 'II 3.8L V-6 gasoline direct injection, DOHC, D-CVVT varia'
 '16V MPFI DOHC Hybrid' 'o'
 '4L V-8 VVT variable valve control, regular unleaded, engi' 'c Motor'
 'DOHC, D-CVVT variable valve control, regular unleaded, en'
 '8 gasoline direct injection, variable valve control, regu']
========================
unique values of cylinders
[6. 8. 4. 3. 0.]
========================
unique values of fuel
['Gasoline' 'Diesel' 'Hybrid' 'E85 Flex Fuel' 'PHEV Hybrid Fuel'
 'Electric' 'Diesel (B20 capable)']
========================
unique values of mileage
[1.000e+01 1.000e+00 0.000e+00 3.200e+01 3.838e+03 5.000e+00 1.500e+01
 2.000e+01 5.320e+02 1.200e+01 8.700e+01 2.500e+01 1.300e+01 3.440e+02
 1.100e+01 7.000e+00 2.000e+00 1.850e+02 1.600e+01 9.000e+00 2.100e+01
 6.000e+00 1.400e+01 8.000e+00 4.357e+03 4.000e+00 3.000e+00 1.480e+02
 5.800e+01 5.900e+01 1.800e+01 3.300e+01 3.000e+01 2.900e+01 4.800e+01
 3.400e+01 4.900e+01 2.460e+02 2.200e+01 1.700e+01 2.600e+01 4.440e+03
 1.050e+02 3.700e+01 2.300e+01 3.500e+01 8.900e+01 6.500e+01 1.900e+01
 3.900e+01 3.100e+01 9.711e+03 9.500e+01 5.400e+01 2.700e+01 4.200e+01
 4.470e+02 7.300e+01 3.990e+02 2.800e+01 2.520e+02 6.800e+01 1.810e+02
 1.860e+02 1.970e+02 7.600e+01 1.880e+02 2.500e+03 3.425e+03 2.077e+03
 2.400e+01 1.750e+02 1.470e+02 6.500e+02 5.100e+01 5.581e+03 4.723e+03
 4.501e+03 5.550e+02 1.946e+03 3.500e+02 8.500e+01 2.410e+02 6.600e+01
 4.100e+01 1.410e+02 2.960e+02]
========================
unique values of transmission
['8-Speed Automatic' 'Automatic' '6-Speed Automatic' 'Automatic CVT'
 '10-Speed Automatic' '8-Speed Automatic with Auto-Shift'
 '7-Speed DSG Automatic with Tiptronic' '8-Speed Automatic with Tiptronic'
 '9-Speed Automatic' '8-speed automatic' 'CVT'
 '7-Speed Automatic S tronic' '7-Speed DSGA? Automatic w/ 4MO'
 '6-Speed Automatic Electronic with Overdrive' '9-Speed 948TE Automatic'
 '8-Speed A/T' 'Variable' '7-Speed Automatic with Auto-Shift'
 '9-Speed A/T' '9 Spd Automatic' 'Aisin 6-Speed Automatic'
 '6-Spd Aisin F21-250 PHEV Auto Trans' '10-Speed Shiftable Automatic'
 '9-speed automatic' '6-SPEED AUTOMATIC' 'automatic w/paddle shifters'
 'A/T' '8-Speed Shiftable Automatic' '6-Speed DCT Automatic' '6-Speed A/T'
 '(CVT) CONT VAR.' 'CVT with Xtronic' '8 Speed Dual Clutch'
 '10-Speed Automatic with Overdrive' '8-Speed Automatic Sport']
========================
unique values of doors
[4. 3. 2.]
========================
unique values of drivetrain
['Four-wheel Drive' 'All-wheel Drive' 'Rear-wheel Drive'

In [39]:
def get_brand_name(car_name):
    car_name = car_name.split(' ')[0]
    return car_name.strip(' ')

In [40]:
get_brand_name('Jeep Wagoneer Series II')

'Jeep'

In [41]:
cars_data['name'] = cars_data['name'].apply(get_brand_name)

In [42]:
cars_data['name'].unique()

array(['Jeep', 'GMC', 'Dodge', 'RAM', 'Nissan', 'Ford', 'Hyundai',
       'Volkswagen', 'Chevrolet', 'Kia', 'Mazda', 'Acura', 'BMW',
       'Toyota', 'Buick', 'Audi', 'Mercedes-Benz', 'Honda', 'Lincoln',
       'Chrysler', 'Cadillac', 'INFINITI', 'Lexus', 'Subaru', 'Land',
       'Volvo'], dtype=object)

In [ ]:
cars_data['name'].replace(['Jeep', 'GMC', 'Dodge', 'RAM', 'Nissan', 'Ford', 'Hyundai',
       'Volkswagen', 'Chevrolet', 'Kia', 'Mazda', 'Acura', 'BMW',
       'Toyota', 'Buick', 'Audi', 'Mercedes-Benz', 'Honda', 'Lincoln',
       'Chrysler', 'Cadillac', 'INFINITI', 'Lexus', 'Subaru', 'Land',
       'Volvo'],[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26],inplace=True)

C:\Users\User\AppData\Local\Temp\ipykernel_13592\2971581735.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  cars_data['name'].replace(['Jeep', 'GMC', 'Dodge', 'RAM', 'Nissan', 'Ford', 'Hyundai',

In [44]:
cars_data['engine'] = cars_data['engine'].apply(get_brand_name)

In [45]:
cars_data['engine'].unique()

array(['24V', 'OHV', '6.2', '16V', '32V', 'ar', 'oled', '4', 'DOHC',
       'gasoline', 'ream', 'MAX', '12V', 'o', 'ne', '6.2L', 'High',
       'TIV-G', '6', 'c', '8', '1.3L', 't', 'oBoost', '>\n\n', '.6L',
       '6.7L', '6.6L', 'der', 'ce', 'Unleaded', '5.3L', 'diesel',
       'EcoBoost', '<dt>VIN</dt>\n', 'ER', 'rbo', 'II', '4L', 'DOHC,'],
      dtype=object)

In [46]:
cars_data['engine'].replace(['24V', 'OHV', '6.2', '16V', '32V', 'ar', 'oled', '4', 'DOHC',
       'gasoline', 'ream', 'MAX', '12V', 'o', 'ne', '6.2L', 'High',
       'TIV-G', '6', 'c', '8', '1.3L', 't', 'oBoost', '>\n\n', '.6L',
       '6.7L', '6.6L', 'der', 'ce', 'Unleaded', '5.3L', 'diesel',
       'EcoBoost', '<dt>VIN</dt>\n', 'ER', 'rbo', 'II', '4L', 'DOHC,'],[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,
                                                                        27,28,29,30,31,32,33,34,35,36,37,38,39,40],inplace=True)

C:\Users\User\AppData\Local\Temp\ipykernel_13592\426614312.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  cars_data['engine'].replace(['24V', 'OHV', '6.2', '16V', '32V', 'ar', 'oled', '4', 'DOHC',

In [47]:
cars_data['fuel'] = cars_data['fuel'].apply(get_brand_name)

In [48]:
cars_data['fuel'].unique()

array(['Gasoline', 'Diesel', 'Hybrid', 'E85', 'PHEV', 'Electric'],
      dtype=object)

In [49]:
cars_data['fuel'].replace(['Gasoline', 'Diesel', 'Hybrid', 'E85', 'PHEV', 'Electric'],[1,2,3,4,5,6],inplace=True)

C:\Users\User\AppData\Local\Temp\ipykernel_13592\1852883338.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  cars_data['fuel'].replace(['Gasoline', 'Diesel', 'Hybrid', 'E85', 'PHEV', 'Electric'],[1,2,3,4,5,6],inplace=True)

In [50]:
cars_data['transmission'] = cars_data['transmission'].apply(get_brand_name)

In [51]:
cars_data['transmission'].unique()

array(['8-Speed', 'Automatic', '6-Speed', '10-Speed', '7-Speed',
       '9-Speed', '8-speed', 'CVT', 'Variable', '9', 'Aisin', '6-Spd',
       '9-speed', '6-SPEED', 'automatic', 'A/T', '(CVT)', '8'],
      dtype=object)

In [53]:
cars_data['transmission'].replace(['8-Speed', 'Automatic', '6-Speed', '10-Speed', '7-Speed',
       '9-Speed', '8-speed', 'CVT', 'Variable', '9', 'Aisin', '6-Spd',
       '9-speed', '6-SPEED', 'automatic', 'A/T', '(CVT)', '8'],[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18],inplace=True)

C:\Users\User\AppData\Local\Temp\ipykernel_13592\2208299736.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  cars_data['transmission'].replace(['8-Speed', 'Automatic', '6-Speed', '10-Speed', '7-Speed',

In [57]:
cars_data['drivetrain'] = cars_data['drivetrain'].apply(get_brand_name)

In [58]:
cars_data['drivetrain'].unique()

array(['Four-wheel', 'All-wheel', 'Rear-wheel', 'Front-wheel'],
      dtype=object)

In [60]:
cars_data['drivetrain'].replace(['Four-wheel', 'All-wheel', 'Rear-wheel', 'Front-wheel'],[1,2,3,4],inplace=True)

C:\Users\User\AppData\Local\Temp\ipykernel_13592\1976265899.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cars_data['drivetrain'].replace(['Four-wheel', 'All-wheel', 'Rear-wheel', 'Front-wheel'],[1,2,3,4],inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_13592\1976265899.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  cars_data['drivetrain'].replace(['Four-wheel', 'All-wheel', 'Rear-wheel', 'Front-wheel'],[1,2,3,4],inplace=True)

In [61]:
cars_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 792 entries, 0 to 1001
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          792 non-null    int64
 1   year          792 non-null    int64
 2   price         792 non-null    float64
 3   engine        792 non-null    int64
 4   cylinders     792 non-null    float64
 5   fuel          792 non-null    int64
 6   mileage       792 non-null    float64
 7   transmission  792 non-null    int64
 8   doors         792 non-null    float64
 9   drivetrain    792 non-null    int64
dtypes: float64(4), int64(6)
memory usage: 68.1 KB

In [62]:
cars_data

,name,year,price,engine,cylinders,fuel,mileage,transmission,doors,drivetrain
0,1,2024,74600.0,1,6.0,1,10.0,1,4.0,1
1,1,2024,50170.0,2,6.0,1,1.0,1,4.0,1
2,2,2024,96410.0,3,8.0,1,0.0,2,4.0,1
3,3,2023,46835.0,4,8.0,1,32.0,1,4.0,2
4,4,2024,81663.0,1,6.0,2,10.0,3,4.0,1
...,...,...,...,...,...,...,...,...,...,...
996,4,2024,69315.0,1,6.0,2,0.0,2,4.0,1
997,17,2024,59037.0,4,4.0,2,10.0,6,3.0,3
999,1,2024,69085.0,1,6.0,1,20.0,1,4.0,1
1000,5,2024,43495.0,19,6.0,1,6.0,2,4.0,2
1001,9,2024,48995.0,21,8.0,1,31.0,2,4.0,3

In [63]:
input_data = cars_data.drop(columns=['price'])
output_data = cars_data['price']

In [64]:
x_train, x_test, y_train, y_test = train_test_split(input_data, output_data, test_size=0.2)

In [ ]:
#model Creation

In [65]:
model = LinearRegression()

In [ ]:
#Train model

In [66]:
model.fit(x_train, y_train)

LinearRegression()

In [67]:
predict = model.predict(x_test)

In [68]:
predict

array([35927.94587591, 43716.08810885, 51566.85894372, 57807.93420969,
       29780.83369951, 41078.01797807, 55944.55276194, 43731.12271481,
       42062.65663712, 44237.52264963, 84828.41353517, 49471.80660686,
       50442.91286102, 56483.88374289, 41111.23403016, 43722.27882895,
       28154.81205636, 71953.71321022, 52800.40098595, 44238.02997511,
       47260.59213028, 68432.32488129, 40559.3147996 , 41046.17998898,
       35193.98017953, 47175.87923362, 48386.81591864, 60188.28333292,
       40559.3147996 , 48920.58940516, 30253.54867151, 49476.22854979,
       68934.56779639, 42729.81584517, 61872.71071114, 51561.55261221,
       49465.65140631, 51573.04966382, 56337.95962622, 42253.10120047,
       58995.59237096, 47260.59213028, 29276.7263289 , 52032.53058898,
       55936.59326467, 72839.84840435, 36167.98896621, 28159.2339993 ,
       40559.3147996 , 43724.04760612, 62461.28203133, 49471.80660686,
       61856.26381164, 42742.56200482, 38895.25206542, 59787.99611756,
       47260.59213028, 42951.13904158, 61906.84538236, 40494.62550599,
       40559.3147996 , 43725.81638329, 38574.38545865, 51333.23553812,
       27051.08602234, 61916.5736568 , 39412.97081005, 29788.29684789,
       48319.93471374, 56329.11574036, 43725.81638329, 44322.78873963,
       33921.19203961, 27048.43285658, 60192.70527585, 87069.56559423,
       35148.04952385, 28187.03808516, 51561.55261221, 49219.6366522 ,
       61850.07309154, 42732.46901093, 47672.88405738, 43722.27882895,
       40559.3147996 , 40559.3147996 , 37393.9728368 , 37351.94587987,
       61911.26732529, 40009.16434622, 30261.50816878, 47265.01407321,
       50497.12289142, 51560.66822362, 42217.72565704, 70560.22472009,
       40559.3147996 , 49476.22854979, 27051.08602234, 44079.01364391,
       63964.53878251, 29446.34667848, 61410.01976479, 48154.55404817,
       48773.9336054 , 55810.58253978, 47260.59213028, 20960.8019773 ,
       50611.57183662, 55823.28208705, 41095.03942301, 47272.08918189,
       43700.91363764, 61852.7262573 , 40387.65962317, 42739.02445048,
       56336.19084905, 38861.75360835, 62164.20246085, 29783.48686527,
       56332.6532947 , 56337.07523763, 43260.32324392, 51569.51210948,
       73917.48837128, 29276.7263289 , 46782.79047641, 42732.46901093,
       44236.63826105, 38856.44727683, 41034.68293736, 65761.90913905,
       43267.3983526 , 51552.70872635, 51560.66822362, 69539.22129663,
       62520.78215063, 42230.99148583, 40565.5055197 , 43250.20692977,
       46092.65732257, 55809.69815119, 37393.9728368 , 48164.28232262,
       43260.32324392, 55941.0152076 , 50585.26091533, 62462.16641991,
       61920.11121114, 47257.05457594, 60186.51455575, 48180.20131717,
       47386.17530947, 41062.13736009, 43724.04760612, 27050.20163376,
       55954.28103639, 73958.33793596, 28165.8127591 ])

In [70]:
x_train.head(1)

,name,year,engine,cylinders,fuel,mileage,transmission,doors,drivetrain
338,3,2023,4,8.0,1,34.0,1,4.0,2

In [74]:
input_data_model = pd.DataFrame(
    [[3,2025,4,8.0,1,34.0,1,4.0,2]],
    columns=['name','year','engine','cylinders','fuel','mileage','transmission','doors','drivetrain'])

In [75]:
input_data_model

,name,year,engine,cylinders,fuel,mileage,transmission,doors,drivetrain
0,3,2025,4,8.0,1,34.0,1,4.0,2

In [76]:
model.predict(input_data_model)

array([69129.733917])

In [77]:
import joblib as jb

In [78]:
jb.dump(model,open('model.joblib','wb'))